// ─────────────────────────────────────────────────────────────────────────────
// Hexode Monaco Editor Themes
// Each key matches the Monaco theme ID (kebab-case) minus the camelCase mapping
// All themes are registered in IDE.jsx's handleBeforeMount()
// ─────────────────────────────────────────────────────────────────────────────

const monacoThemes = {
  // ── 1. Midnight Aurora (Hexode Default Dark) ───────────────────────────────
  midnightAurora: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "D4D7DD", background: "0D1117" },
      { token: "comment", foreground: "7F8C98", fontStyle: "italic" },
      { token: "keyword", foreground: "C792EA", fontStyle: "bold" },
      { token: "operator", foreground: "89DDFF" },
      { token: "number", foreground: "F78C6C" },
      { token: "string", foreground: "C3E88D" },
      { token: "regexp", foreground: "FFD866" },
      { token: "type", foreground: "82AAFF" },
      { token: "type.identifier", foreground: "82AAFF" },
      { token: "delimiter", foreground: "89A1B5" },
      { token: "delimiter.bracket", foreground: "A9B7C6" },
      { token: "tag", foreground: "F07178" },
      { token: "attribute.name", foreground: "FFCB6B" },
      { token: "attribute.value", foreground: "C3E88D" },
      { token: "identifier", foreground: "EEFFFF" },
      { token: "function", foreground: "82AAFF" },
      { token: "function.call", foreground: "82AAFF" },
      { token: "variable", foreground: "EEFFFF" },
      { token: "variable.predefined", foreground: "F07178" },
      { token: "constant", foreground: "F78C6C" },
      { token: "constant.numeric", foreground: "F78C6C" },
    ],
    colors: {
      "editor.background": "#0D1117",
      "editor.foreground": "#D4D7DD",
      "editorLineNumber.foreground": "#4B5563",
      "editorLineNumber.activeForeground": "#9FB3C8",
      "editorCursor.foreground": "#FFCC66",
      "editor.selectionBackground": "#264F78",
      "editor.inactiveSelectionBackground": "#1F2A37",
      "editor.selectionHighlightBackground": "#2D3A4B",
      "editor.wordHighlightBackground": "#223249",
      "editor.wordHighlightStrongBackground": "#2F4366",
      "editor.findMatchBackground": "#42557B",
      "editor.findMatchHighlightBackground": "#2C3A52",
      "editorHoverWidget.background": "#161B22",
      "editorHoverWidget.border": "#30363D",
      "editorWidget.background": "#161B22",
      "editorWidget.border": "#30363D",
      "editorSuggestWidget.background": "#161B22",
      "editorSuggestWidget.border": "#30363D",
      "editorSuggestWidget.selectedBackground": "#223249",
      "editorSuggestWidget.foreground": "#D4D7DD",
      "editorSuggestWidget.highlightForeground": "#82AAFF",
      "editor.lineHighlightBackground": "#11161D",
      "editorIndentGuide.background1": "#1F2937",
      "editorIndentGuide.activeBackground1": "#3B4A5C",
      "editorWhitespace.foreground": "#2A3441",
      "editorBracketMatch.background": "#2D3A4B",
      "editorBracketMatch.border": "#82AAFF",
      "editorGutter.background": "#0D1117",
      "editorError.foreground": "#F07178",
      "editorWarning.foreground": "#FFCB6B",
      "editorInfo.foreground": "#82AAFF",
      "editorHint.foreground": "#4EC9B0",
      "minimap.background": "#0D1117",
      minimapSelectionHighlight: "#264F78",
      "scrollbarSlider.background": "#2A344180",
      "scrollbarSlider.hoverBackground": "#3B4A5CB3",
      "scrollbarSlider.activeBackground": "#4B5D73CC",
    },
  },

  // ── 2. Morning Aurora (Hexode Default Light) ──────────────────────────────
  morningAurora: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "", foreground: "2A2F36", background: "F7F9FC" },
      { token: "comment", foreground: "7A8594", fontStyle: "italic" },
      { token: "keyword", foreground: "7C4DFF", fontStyle: "bold" },
      { token: "operator", foreground: "0F6CBD" },
      { token: "number", foreground: "C75B12" },
      { token: "string", foreground: "2E7D32" },
      { token: "regexp", foreground: "B26A00" },
      { token: "type", foreground: "1565C0" },
      { token: "type.identifier", foreground: "1565C0" },
      { token: "delimiter", foreground: "7C8796" },
      { token: "delimiter.bracket", foreground: "5C6773" },
      { token: "tag", foreground: "D6336C" },
      { token: "attribute.name", foreground: "9C6B00" },
      { token: "attribute.value", foreground: "2E7D32" },
      { token: "identifier", foreground: "2A2F36" },
      { token: "function", foreground: "0066CC" },
      { token: "function.call", foreground: "0066CC" },
      { token: "variable", foreground: "2A2F36" },
      { token: "variable.predefined", foreground: "C2185B" },
      { token: "constant", foreground: "C75B12" },
      { token: "constant.numeric", foreground: "C75B12" },
    ],
    colors: {
      "editor.background": "#F7F9FC",
      "editor.foreground": "#2A2F36",
      "editorLineNumber.foreground": "#A0A8B3",
      "editorLineNumber.activeForeground": "#5B6572",
      "editorCursor.foreground": "#7C4DFF",
      "editor.selectionBackground": "#DCEBFF",
      "editor.inactiveSelectionBackground": "#EAF2FC",
      "editor.selectionHighlightBackground": "#E8F1FF",
      "editor.wordHighlightBackground": "#E3EEFF",
      "editor.wordHighlightStrongBackground": "#D6E7FF",
      "editor.findMatchBackground": "#BDD7FF",
      "editor.findMatchHighlightBackground": "#E3EEFF",
      "editorHoverWidget.background": "#FFFFFF",
      "editorHoverWidget.border": "#D7DEE7",
      "editorWidget.background": "#FFFFFF",
      "editorWidget.border": "#D7DEE7",
      "editorSuggestWidget.background": "#FFFFFF",
      "editorSuggestWidget.border": "#D7DEE7",
      "editorSuggestWidget.selectedBackground": "#EEF4FF",
      "editorSuggestWidget.foreground": "#2A2F36",
      "editorSuggestWidget.highlightForeground": "#0066CC",
      "editor.lineHighlightBackground": "#F0F4F8",
      "editorIndentGuide.background1": "#E1E7EF",
      "editorIndentGuide.activeBackground1": "#B8C4D4",
      "editorWhitespace.foreground": "#D3DCE6",
      "editorBracketMatch.background": "#EAF2FF",
      "editorBracketMatch.border": "#4C84FF",
      "editorGutter.background": "#F7F9FC",
      "editorError.foreground": "#D32F2F",
      "editorWarning.foreground": "#ED6C02",
      "editorInfo.foreground": "#0288D1",
      "editorHint.foreground": "#2E7D32",
      "minimap.background": "#F7F9FC",
      minimapSelectionHighlight: "#CFE2FF",
      "scrollbarSlider.background": "#BCC7D533",
      "scrollbarSlider.hoverBackground": "#98A8BA66",
      "scrollbarSlider.activeBackground": "#7F91A6AA",
    },
  },

  // ── 3. Tokyo Night ────────────────────────────────────────────────────────
  tokyoNight: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "A9B1D6", background: "1A1B2E" },
      { token: "comment", foreground: "565F89", fontStyle: "italic" },
      { token: "keyword", foreground: "BB9AF7", fontStyle: "bold" },
      { token: "operator", foreground: "89DDFF" },
      { token: "number", foreground: "FF9E64" },
      { token: "string", foreground: "9ECE6A" },
      { token: "regexp", foreground: "B4F9F8" },
      { token: "type", foreground: "2AC3DE" },
      { token: "type.identifier", foreground: "2AC3DE" },
      { token: "delimiter", foreground: "C0CAF5" },
      { token: "delimiter.bracket", foreground: "89DDFF" },
      { token: "tag", foreground: "F7768E" },
      { token: "attribute.name", foreground: "E0AF68" },
      { token: "attribute.value", foreground: "9ECE6A" },
      { token: "identifier", foreground: "C0CAF5" },
      { token: "function", foreground: "7AA2F7" },
      { token: "function.call", foreground: "7AA2F7" },
      { token: "variable", foreground: "C0CAF5" },
      { token: "variable.predefined", foreground: "F7768E" },
      { token: "constant", foreground: "FF9E64" },
      { token: "constant.numeric", foreground: "FF9E64" },
    ],
    colors: {
      "editor.background": "#1A1B2E",
      "editor.foreground": "#A9B1D6",
      "editorLineNumber.foreground": "#3B4261",
      "editorLineNumber.activeForeground": "#737AA2",
      "editorCursor.foreground": "#C0CAF5",
      "editor.selectionBackground": "#283457",
      "editor.inactiveSelectionBackground": "#1F2335",
      "editor.selectionHighlightBackground": "#1F2335",
      "editor.wordHighlightBackground": "#1F2335",
      "editor.wordHighlightStrongBackground": "#283457",
      "editor.findMatchBackground": "#3D59A1",
      "editor.findMatchHighlightBackground": "#1F2335",
      "editorHoverWidget.background": "#1F2335",
      "editorHoverWidget.border": "#292E42",
      "editorWidget.background": "#1F2335",
      "editorWidget.border": "#292E42",
      "editorSuggestWidget.background": "#1F2335",
      "editorSuggestWidget.border": "#292E42",
      "editorSuggestWidget.selectedBackground": "#283457",
      "editorSuggestWidget.foreground": "#A9B1D6",
      "editorSuggestWidget.highlightForeground": "#7AA2F7",
      "editor.lineHighlightBackground": "#1F2335",
      "editorIndentGuide.background1": "#232433",
      "editorIndentGuide.activeBackground1": "#3B4261",
      "editorBracketMatch.background": "#1F2335",
      "editorBracketMatch.border": "#89DDFF",
      "editorGutter.background": "#1A1B2E",
      "editorError.foreground": "#F7768E",
      "editorWarning.foreground": "#E0AF68",
      "editorInfo.foreground": "#7AA2F7",
      "minimap.background": "#1A1B2E",
      "scrollbarSlider.background": "#28345780",
      "scrollbarSlider.hoverBackground": "#283457B3",
      "scrollbarSlider.activeBackground": "#3D5996CC",
    },
  },

  // ── 4. Dracula ────────────────────────────────────────────────────────────
  dracula: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "F8F8F2", background: "282A36" },
      { token: "comment", foreground: "6272A4", fontStyle: "italic" },
      { token: "keyword", foreground: "FF79C6", fontStyle: "bold" },
      { token: "operator", foreground: "FF79C6" },
      { token: "number", foreground: "BD93F9" },
      { token: "string", foreground: "F1FA8C" },
      { token: "regexp", foreground: "FF5555" },
      { token: "type", foreground: "8BE9FD" },
      { token: "type.identifier", foreground: "8BE9FD" },
      { token: "delimiter", foreground: "F8F8F2" },
      { token: "delimiter.bracket", foreground: "F8F8F2" },
      { token: "tag", foreground: "FF79C6" },
      { token: "attribute.name", foreground: "50FA7B" },
      { token: "attribute.value", foreground: "F1FA8C" },
      { token: "identifier", foreground: "F8F8F2" },
      { token: "function", foreground: "50FA7B" },
      { token: "function.call", foreground: "50FA7B" },
      { token: "variable", foreground: "F8F8F2" },
      { token: "variable.predefined", foreground: "BD93F9" },
      { token: "constant", foreground: "BD93F9" },
      { token: "constant.numeric", foreground: "BD93F9" },
    ],
    colors: {
      "editor.background": "#282A36",
      "editor.foreground": "#F8F8F2",
      "editorLineNumber.foreground": "#6272A4",
      "editorLineNumber.activeForeground": "#F8F8F2",
      "editorCursor.foreground": "#F8F8F2",
      "editor.selectionBackground": "#44475A",
      "editor.inactiveSelectionBackground": "#343746",
      "editor.selectionHighlightBackground": "#343746",
      "editor.wordHighlightBackground": "#343746",
      "editor.wordHighlightStrongBackground": "#44475A",
      "editor.findMatchBackground": "#FFB86C50",
      "editor.findMatchHighlightBackground": "#44475A",
      "editorHoverWidget.background": "#21222C",
      "editorHoverWidget.border": "#6272A4",
      "editorWidget.background": "#21222C",
      "editorWidget.border": "#6272A4",
      "editorSuggestWidget.background": "#21222C",
      "editorSuggestWidget.border": "#6272A4",
      "editorSuggestWidget.selectedBackground": "#44475A",
      "editorSuggestWidget.foreground": "#F8F8F2",
      "editorSuggestWidget.highlightForeground": "#50FA7B",
      "editor.lineHighlightBackground": "#44475A50",
      "editorIndentGuide.background1": "#3B3F51",
      "editorIndentGuide.activeBackground1": "#6272A4",
      "editorBracketMatch.background": "#44475A",
      "editorBracketMatch.border": "#FF79C6",
      "editorGutter.background": "#282A36",
      "editorError.foreground": "#FF5555",
      "editorWarning.foreground": "#FFB86C",
      "editorInfo.foreground": "#8BE9FD",
      "minimap.background": "#282A36",
      "scrollbarSlider.background": "#44475A80",
      "scrollbarSlider.hoverBackground": "#44475AB3",
      "scrollbarSlider.activeBackground": "#6272A4CC",
    },
  },

  // ── 5. GitHub Light ───────────────────────────────────────────────────────
  githubLight: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "", foreground: "1F2328", background: "FFFFFF" },
      { token: "comment", foreground: "6E7781", fontStyle: "italic" },
      { token: "keyword", foreground: "CF222E", fontStyle: "bold" },
      { token: "operator", foreground: "CF222E" },
      { token: "number", foreground: "0550AE" },
      { token: "string", foreground: "0A3069" },
      { token: "regexp", foreground: "116329" },
      { token: "type", foreground: "8250DF" },
      { token: "type.identifier", foreground: "8250DF" },
      { token: "delimiter", foreground: "1F2328" },
      { token: "delimiter.bracket", foreground: "1F2328" },
      { token: "tag", foreground: "116329" },
      { token: "attribute.name", foreground: "0550AE" },
      { token: "attribute.value", foreground: "0A3069" },
      { token: "identifier", foreground: "1F2328" },
      { token: "function", foreground: "8250DF" },
      { token: "function.call", foreground: "8250DF" },
      { token: "variable", foreground: "953800" },
      { token: "variable.predefined", foreground: "CF222E" },
      { token: "constant", foreground: "0550AE" },
      { token: "constant.numeric", foreground: "0550AE" },
    ],
    colors: {
      "editor.background": "#FFFFFF",
      "editor.foreground": "#1F2328",
      "editorLineNumber.foreground": "#8C959F",
      "editorLineNumber.activeForeground": "#1F2328",
      "editorCursor.foreground": "#0969DA",
      "editor.selectionBackground": "#ADD6FF80",
      "editor.inactiveSelectionBackground": "#ADD6FF40",
      "editor.selectionHighlightBackground": "#ADD6FF40",
      "editor.wordHighlightBackground": "#ADD6FF40",
      "editor.wordHighlightStrongBackground": "#ADD6FF80",
      "editor.findMatchBackground": "#FFD33D80",
      "editor.findMatchHighlightBackground": "#ADD6FF40",
      "editorHoverWidget.background": "#FFFFFF",
      "editorHoverWidget.border": "#D0D7DE",
      "editorWidget.background": "#FFFFFF",
      "editorWidget.border": "#D0D7DE",
      "editorSuggestWidget.background": "#FFFFFF",
      "editorSuggestWidget.border": "#D0D7DE",
      "editorSuggestWidget.selectedBackground": "#DDF4FF",
      "editorSuggestWidget.foreground": "#1F2328",
      "editorSuggestWidget.highlightForeground": "#0969DA",
      "editor.lineHighlightBackground": "#F6F8FA",
      "editorIndentGuide.background1": "#EEF0F2",
      "editorIndentGuide.activeBackground1": "#D0D7DE",
      "editorBracketMatch.background": "#DDF4FF",
      "editorBracketMatch.border": "#0969DA",
      "editorGutter.background": "#FFFFFF",
      "editorError.foreground": "#CF222E",
      "editorWarning.foreground": "#9A6700",
      "editorInfo.foreground": "#0969DA",
      "minimap.background": "#FFFFFF",
      "scrollbarSlider.background": "#D0D7DE40",
      "scrollbarSlider.hoverBackground": "#D0D7DE80",
      "scrollbarSlider.activeBackground": "#8C959FAA",
    },
  },

  // ── 6. Solarized Dark ─────────────────────────────────────────────────────
  solarizedDark: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "839496", background: "002B36" },
      { token: "comment", foreground: "586E75", fontStyle: "italic" },
      { token: "keyword", foreground: "859900", fontStyle: "bold" },
      { token: "operator", foreground: "859900" },
      { token: "number", foreground: "D33682" },
      { token: "string", foreground: "2AA198" },
      { token: "regexp", foreground: "DC322F" },
      { token: "type", foreground: "268BD2" },
      { token: "type.identifier", foreground: "268BD2" },
      { token: "delimiter", foreground: "93A1A1" },
      { token: "delimiter.bracket", foreground: "93A1A1" },
      { token: "tag", foreground: "268BD2" },
      { token: "attribute.name", foreground: "657B83" },
      { token: "attribute.value", foreground: "2AA198" },
      { token: "identifier", foreground: "839496" },
      { token: "function", foreground: "268BD2" },
      { token: "function.call", foreground: "268BD2" },
      { token: "variable", foreground: "839496" },
      { token: "variable.predefined", foreground: "CB4B16" },
      { token: "constant", foreground: "CB4B16" },
      { token: "constant.numeric", foreground: "D33682" },
    ],
    colors: {
      "editor.background": "#002B36",
      "editor.foreground": "#839496",
      "editorLineNumber.foreground": "#2E4E58",
      "editorLineNumber.activeForeground": "#586E75",
      "editorCursor.foreground": "#839496",
      "editor.selectionBackground": "#073642",
      "editor.inactiveSelectionBackground": "#05303A",
      "editor.selectionHighlightBackground": "#073642",
      "editor.wordHighlightBackground": "#073642",
      "editor.wordHighlightStrongBackground": "#0A4A5E",
      "editor.findMatchBackground": "#0D6E8A60",
      "editor.findMatchHighlightBackground": "#073642",
      "editorHoverWidget.background": "#002B36",
      "editorHoverWidget.border": "#073642",
      "editorWidget.background": "#002B36",
      "editorWidget.border": "#073642",
      "editorSuggestWidget.background": "#002B36",
      "editorSuggestWidget.border": "#073642",
      "editorSuggestWidget.selectedBackground": "#073642",
      "editorSuggestWidget.foreground": "#839496",
      "editorSuggestWidget.highlightForeground": "#268BD2",
      "editor.lineHighlightBackground": "#00212B",
      "editorIndentGuide.background1": "#073642",
      "editorIndentGuide.activeBackground1": "#0D4A5C",
      "editorBracketMatch.background": "#073642",
      "editorBracketMatch.border": "#268BD2",
      "editorGutter.background": "#002B36",
      "editorError.foreground": "#DC322F",
      "editorWarning.foreground": "#B58900",
      "editorInfo.foreground": "#268BD2",
      "minimap.background": "#002B36",
      "scrollbarSlider.background": "#07364280",
      "scrollbarSlider.hoverBackground": "#0736428C",
      "scrollbarSlider.activeBackground": "#0D4A5CAA",
    },
  },

  // ── 7. Neon Nights ────────────────────────────────────────────────────────
  neonNights: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "E0E0E0", background: "262335" },
      { token: "comment", foreground: "848CB5", fontStyle: "italic" },
      { token: "keyword", foreground: "FF79C6", fontStyle: "bold" },
      { token: "operator", foreground: "FF79C6" },
      { token: "number", foreground: "Fede5d" },
      { token: "string", foreground: "36F9F6" },
      { token: "regexp", foreground: "Fede5d" },
      { token: "type", foreground: "36F9F6" },
      { token: "type.identifier", foreground: "36F9F6" },
      { token: "delimiter", foreground: "E0E0E0" },
      { token: "delimiter.bracket", foreground: "848CB5" },
      { token: "tag", foreground: "FF79C6" },
      { token: "attribute.name", foreground: "36F9F6" },
      { token: "attribute.value", foreground: "Fede5d" },
      { token: "identifier", foreground: "E0E0E0" },
      { token: "function", foreground: "Fede5d" },
      { token: "function.call", foreground: "Fede5d" },
      { token: "variable", foreground: "E0E0E0" },
      { token: "variable.predefined", foreground: "FF79C6" },
      { token: "constant", foreground: "Fede5d" },
      { token: "constant.numeric", foreground: "Fede5d" },
    ],
    colors: {
      "editor.background": "#262335",
      "editor.foreground": "#E0E0E0",
      "editorLineNumber.foreground": "#615C76",
      "editorLineNumber.activeForeground": "#FF79C6",
      "editorCursor.foreground": "#FF79C6",
      "editor.selectionBackground": "#423769",
      "editor.inactiveSelectionBackground": "#302B45",
      "editor.selectionHighlightBackground": "#3A3258",
      "editor.wordHighlightBackground": "#3A3258",
      "editor.wordHighlightStrongBackground": "#423769",
      "editor.findMatchBackground": "#FF79C660",
      "editor.findMatchHighlightBackground": "#423769",
      "editorHoverWidget.background": "#1E1A2B",
      "editorHoverWidget.border": "#FF79C650",
      "editorWidget.background": "#1E1A2B",
      "editorWidget.border": "#FF79C650",
      "editorSuggestWidget.background": "#1E1A2B",
      "editorSuggestWidget.border": "#FF79C650",
      "editorSuggestWidget.selectedBackground": "#423769",
      "editorSuggestWidget.foreground": "#E0E0E0",
      "editorSuggestWidget.highlightForeground": "#36F9F6",
      "editor.lineHighlightBackground": "#302B4550",
      "editorIndentGuide.background1": "#3A3258",
      "editorIndentGuide.activeBackground1": "#615C76",
      "editorBracketMatch.background": "#423769",
      "editorBracketMatch.border": "#36F9F6",
      "editorGutter.background": "#262335",
      "editorError.foreground": "#FF453A",
      "editorWarning.foreground": "#FFD60A",
      "editorInfo.foreground": "#36F9F6",
      "minimap.background": "#262335",
      "scrollbarSlider.background": "#42376980",
      "scrollbarSlider.hoverBackground": "#423769B3",
      "scrollbarSlider.activeBackground": "#615C76CC",
    },
  },

  // ── 8. Oceanic Abyss ──────────────────────────────────────────────────────
  oceanicAbyss: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "CDD3DE", background: "0F111A" },
      { token: "comment", foreground: "546E7A", fontStyle: "italic" },
      { token: "keyword", foreground: "C792EA", fontStyle: "bold" },
      { token: "operator", foreground: "89DDFF" },
      { token: "number", foreground: "F78C6C" },
      { token: "string", foreground: "C3E88D" },
      { token: "regexp", foreground: "FFCB6B" },
      { token: "type", foreground: "FFCB6B" },
      { token: "type.identifier", foreground: "FFCB6B" },
      { token: "delimiter", foreground: "89DDFF" },
      { token: "delimiter.bracket", foreground: "89DDFF" },
      { token: "tag", foreground: "F07178" },
      { token: "attribute.name", foreground: "C792EA" },
      { token: "attribute.value", foreground: "C3E88D" },
      { token: "identifier", foreground: "CDD3DE" },
      { token: "function", foreground: "82AAFF" },
      { token: "function.call", foreground: "82AAFF" },
      { token: "variable", foreground: "CDD3DE" },
      { token: "variable.predefined", foreground: "F07178" },
      { token: "constant", foreground: "F78C6C" },
      { token: "constant.numeric", foreground: "F78C6C" },
    ],
    colors: {
      "editor.background": "#0F111A",
      "editor.foreground": "#CDD3DE",
      "editorLineNumber.foreground": "#37474F",
      "editorLineNumber.activeForeground": "#546E7A",
      "editorCursor.foreground": "#FFCC00",
      "editor.selectionBackground": "#1F2233",
      "editor.inactiveSelectionBackground": "#161925",
      "editor.selectionHighlightBackground": "#1B1E2B",
      "editor.wordHighlightBackground": "#1B1E2B",
      "editor.wordHighlightStrongBackground": "#1F2233",
      "editor.findMatchBackground": "#FFCB6B60",
      "editor.findMatchHighlightBackground": "#1F2233",
      "editorHoverWidget.background": "#090B10",
      "editorHoverWidget.border": "#1F2233",
      "editorWidget.background": "#090B10",
      "editorWidget.border": "#1F2233",
      "editorSuggestWidget.background": "#090B10",
      "editorSuggestWidget.border": "#1F2233",
      "editorSuggestWidget.selectedBackground": "#1F2233",
      "editorSuggestWidget.foreground": "#CDD3DE",
      "editorSuggestWidget.highlightForeground": "#82AAFF",
      "editor.lineHighlightBackground": "#141722",
      "editorIndentGuide.background1": "#1F2233",
      "editorIndentGuide.activeBackground1": "#37474F",
      "editorBracketMatch.background": "#1F2233",
      "editorBracketMatch.border": "#89DDFF",
      "editorGutter.background": "#0F111A",
      "editorError.foreground": "#F07178",
      "editorWarning.foreground": "#FFCB6B",
      "editorInfo.foreground": "#82AAFF",
      "minimap.background": "#0F111A",
      "scrollbarSlider.background": "#1F223380",
      "scrollbarSlider.hoverBackground": "#1F2233B3",
      "scrollbarSlider.activeBackground": "#37474FCC",
    },
  },

  // ── 9. Rose Pine Dawn ─────────────────────────────────────────────────────
  rosePineDawn: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "", foreground: "575279", background: "FAF4ED" },
      { token: "comment", foreground: "9893A5", fontStyle: "italic" },
      { token: "keyword", foreground: "286983", fontStyle: "bold" },
      { token: "operator", foreground: "797593" },
      { token: "number", foreground: "D7827E" },
      { token: "string", foreground: "EA9D34" },
      { token: "regexp", foreground: "B4637A" },
      { token: "type", foreground: "56949F" },
      { token: "type.identifier", foreground: "56949F" },
      { token: "delimiter", foreground: "797593" },
      { token: "delimiter.bracket", foreground: "797593" },
      { token: "tag", foreground: "286983" },
      { token: "attribute.name", foreground: "D7827E" },
      { token: "attribute.value", foreground: "EA9D34" },
      { token: "identifier", foreground: "575279" },
      { token: "function", foreground: "D7827E" },
      { token: "function.call", foreground: "D7827E" },
      { token: "variable", foreground: "575279" },
      { token: "variable.predefined", foreground: "B4637A" },
      { token: "constant", foreground: "D7827E" },
      { token: "constant.numeric", foreground: "D7827E" },
    ],
    colors: {
      "editor.background": "#FAF4ED",
      "editor.foreground": "#575279",
      "editorLineNumber.foreground": "#CECACD",
      "editorLineNumber.activeForeground": "#797593",
      "editorCursor.foreground": "#575279",
      "editor.selectionBackground": "#DFDAD9",
      "editor.inactiveSelectionBackground": "#F2E9E1",
      "editor.selectionHighlightBackground": "#F2E9E1",
      "editor.wordHighlightBackground": "#F2E9E1",
      "editor.wordHighlightStrongBackground": "#DFDAD9",
      "editor.findMatchBackground": "#EA9D3460",
      "editor.findMatchHighlightBackground": "#DFDAD9",
      "editorHoverWidget.background": "#FFFFAF",
      "editorHoverWidget.border": "#DFDAD9",
      "editorWidget.background": "#FFFFAF",
      "editorWidget.border": "#DFDAD9",
      "editorSuggestWidget.background": "#FFFFAF",
      "editorSuggestWidget.border": "#DFDAD9",
      "editorSuggestWidget.selectedBackground": "#DFDAD9",
      "editorSuggestWidget.foreground": "#575279",
      "editorSuggestWidget.highlightForeground": "#286983",
      "editor.lineHighlightBackground": "#F2E9E150",
      "editorIndentGuide.background1": "#DFDAD9",
      "editorIndentGuide.activeBackground1": "#CECACD",
      "editorBracketMatch.background": "#DFDAD9",
      "editorBracketMatch.border": "#56949F",
      "editorGutter.background": "#FAF4ED",
      "editorError.foreground": "#B4637A",
      "editorWarning.foreground": "#EA9D34",
      "editorInfo.foreground": "#56949F",
      "minimap.background": "#FAF4ED",
      "scrollbarSlider.background": "#DFDAD980",
      "scrollbarSlider.hoverBackground": "#DFDAD9B3",
      "scrollbarSlider.activeBackground": "#CECACDCC",
    },
  },

  // ── 10. Arctic Frost ──────────────────────────────────────────────────────
  arcticFrost: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "", foreground: "24292F", background: "F3F6FA" },
      { token: "comment", foreground: "6E7781", fontStyle: "italic" },
      { token: "keyword", foreground: "6F42C1", fontStyle: "bold" },
      { token: "operator", foreground: "008080" },
      { token: "number", foreground: "005CC5" },
      { token: "string", foreground: "0A3069" },
      { token: "regexp", foreground: "D73A49" },
      { token: "type", foreground: "E36209" },
      { token: "type.identifier", foreground: "E36209" },
      { token: "delimiter", foreground: "24292F" },
      { token: "delimiter.bracket", foreground: "24292F" },
      { token: "tag", foreground: "22863A" },
      { token: "attribute.name", foreground: "6F42C1" },
      { token: "attribute.value", foreground: "0A3069" },
      { token: "identifier", foreground: "24292F" },
      { token: "function", foreground: "6F42C1" },
      { token: "function.call", foreground: "6F42C1" },
      { token: "variable", foreground: "E36209" },
      { token: "variable.predefined", foreground: "D73A49" },
      { token: "constant", foreground: "005CC5" },
      { token: "constant.numeric", foreground: "005CC5" },
    ],
    colors: {
      "editor.background": "#F3F6FA",
      "editor.foreground": "#24292F",
      "editorLineNumber.foreground": "#8C959F",
      "editorLineNumber.activeForeground": "#24292F",
      "editorCursor.foreground": "#0A3069",
      "editor.selectionBackground": "#B3D4FF",
      "editor.inactiveSelectionBackground": "#D1E4FF",
      "editor.selectionHighlightBackground": "#D1E4FF",
      "editor.wordHighlightBackground": "#E6F0FF",
      "editor.wordHighlightStrongBackground": "#B3D4FF",
      "editor.findMatchBackground": "#FFDF5D80",
      "editor.findMatchHighlightBackground": "#B3D4FF",
      "editorHoverWidget.background": "#FFFFFF",
      "editorHoverWidget.border": "#D0D7DE",
      "editorWidget.background": "#FFFFFF",
      "editorWidget.border": "#D0D7DE",
      "editorSuggestWidget.background": "#FFFFFF",
      "editorSuggestWidget.border": "#D0D7DE",
      "editorSuggestWidget.selectedBackground": "#E6F0FF",
      "editorSuggestWidget.foreground": "#24292F",
      "editorSuggestWidget.highlightForeground": "#6F42C1",
      "editor.lineHighlightBackground": "#EAF0F6",
      "editorIndentGuide.background1": "#E1E4E8",
      "editorIndentGuide.activeBackground1": "#D0D7DE",
      "editorBracketMatch.background": "#D1E4FF",
      "editorBracketMatch.border": "#008080",
      "editorGutter.background": "#F3F6FA",
      "editorError.foreground": "#D73A49",
      "editorWarning.foreground": "#B08800",
      "editorInfo.foreground": "#005CC5",
      "minimap.background": "#F3F6FA",
      "scrollbarSlider.background": "#D0D7DE60",
      "scrollbarSlider.hoverBackground": "#D0D7DE90",
      "scrollbarSlider.activeBackground": "#8C959FCC",
    },
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// UI metadata consumed by the Theme Picker in IDEHeader
// `color` is the accent color shown as the swatch dot
// `dark` indicates if this is a dark-base theme
// ─────────────────────────────────────────────────────────────────────────────
export const THEME_METADATA = [
  {
    id: "midnight-aurora",
    label: "Midnight Aurora",
    dark: true,
    color: "#82AAFF",
    description: "Hexode default dark",
  },
  {
    id: "tokyo-night",
    label: "Tokyo Night",
    dark: true,
    color: "#BB9AF7",
    description: "Neon purple nights",
  },
  {
    id: "dracula",
    label: "Dracula",
    dark: true,
    color: "#FF79C6",
    description: "Legendary purple dark",
  },
  {
    id: "solarized-dark",
    label: "Solarized Dark",
    dark: true,
    color: "#268BD2",
    description: "Warm amber on teal",
  },
  {
    id: "morning-aurora",
    label: "Morning Aurora",
    dark: false,
    color: "#7C4DFF",
    description: "Hexode default light",
  },
  {
    id: "github-light",
    label: "GitHub Light",
    dark: false,
    color: "#0969DA",
    description: "GitHub web editor",
  },
  {
    id: "neon-nights",
    label: "Neon Nights",
    dark: true,
    color: "#FF79C6",
    description: "Retro-futuristic synthwave",
  },
  {
    id: "oceanic-abyss",
    label: "Oceanic Abyss",
    dark: true,
    color: "#5FB3B3",
    description: "Deep sea legibility",
  },
  {
    id: "rose-pine-dawn",
    label: "Rose Pine Dawn",
    dark: false,
    color: "#D7827E",
    description: "Soothing warm pastel",
  },
  {
    id: "arctic-frost",
    label: "Arctic Frost",
    dark: false,
    color: "#6F42C1",
    description: "Crisp cool icy white",
  },
  // ── Built-in Monaco themes (no defineTheme needed) ──────────────────────
  {
    id: "vs-dark",
    label: "VS Dark",
    dark: true,
    color: "#569CD6",
    description: "Monaco classic dark",
    builtin: true,
  },
  {
    id: "hc-black",
    label: "High Contrast",
    dark: true,
    color: "#FFFFFF",
    description: "Maximum readability",
    builtin: true,
  },
  {
    id: "vs",
    label: "VS Light",
    dark: false,
    color: "#0000FF",
    description: "Monaco classic light",
    builtin: true,
  },
];

export default monacoThemes;
